# Generated by Django 5.2.17 on 2026-10-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0029_jadawel_rename_local_jadawel_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflowhistory",
            name="cancellation_requested_by",
            field=models.ForeignKey(
                blank=True,
                db_default=None,
                help_text="The user who requested the cancellation of this run.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="automationworkflowhistory",
            name="cancellation_requested_on",
            field=models.DateTimeField(
                blank=True,
                db_default=None,
                help_text="When the cancellation of this run was requested.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="automationnodehistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("error", "Error"),
                    ("disabled", "Disabled"),
                    ("started", "Started"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="automationworkflowhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("error", "Error"),
                    ("disabled", "Disabled"),
                    ("started", "Started"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=16,
            ),
        ),
    ]
