# Generated by Django 5.2.17 on 2026-09-26 16:59

import django.db.models.deletion
import jadawel.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0018_mcp_protection_database_vault'),
        ('core', '0117_jadawel_rename_show_help_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanadChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', help_text='`<provider type>/<model name>` used for the last turn.', max_length=255)),
                ('history', models.JSONField(default=list, help_text='The pydantic-ai message history, in its JSON form.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ('-updated_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SanadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting Approval'), ('done', 'Done'), ('error', 'Error')], default='done', max_length=32)),
                ('content', models.TextField(blank=True, default='')),
                ('context', models.JSONField(default=dict, help_text='What the user was looking at: `table_id`, `view_id`.')),
                ('actions', models.JSONField(default=list, help_text='Every tool Sanad called while producing this message.')),
                ('approvals', models.JSONField(default=list, help_text='Destructive tool calls the model asked for. Each gets an `approved` key once the user decides.')),
                ('error', models.CharField(blank=True, default='', help_text='A stable error code the panel translates.', max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='arabase.sanadchat')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
