# Generated by Django 5.2.17 on 2026-09-27 05:10

import django.db.models.deletion
import jadawel.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0019_sanad_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerativeAIProviderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('provider', models.CharField(help_text='The core generative AI model type, e.g. `openai`.', max_length=32, unique=True)),
                ('api_key_sealed', models.TextField(blank=True, default='', help_text='The API key, encrypted with a key derived from SECRET_KEY.')),
                ('api_key_hint', models.CharField(blank=True, default='', help_text="The key's last characters, shown so admins can recognise it.", max_length=8)),
                ('enabled_models', models.JSONField(default=list, help_text='Enabled model names.')),
                ('host', models.CharField(blank=True, default='', help_text='Ollama only.', max_length=500)),
                ('base_url', models.CharField(blank=True, default='', help_text='OpenAI only, optional.', max_length=500)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider',),
            },
        ),
    ]
