# Generated by Django 5.2.17 on 2026-09-27 20:40

import django.db.models.deletion
import jadawel.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0020_generative_ai_provider_settings'),
        ('core', '0117_jadawel_rename_show_help_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanadBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('monthly_turn_limit', models.PositiveIntegerField(blank=True, help_text='Messages Sanad may answer per calendar month (UTC).', null=True)),
                ('monthly_token_limit', models.PositiveBigIntegerField(blank=True, help_text='Model tokens, input plus output, per calendar month (UTC).', null=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanadUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month.')),
                ('turns', models.PositiveIntegerField(default=0, help_text='Messages sent to Sanad (an approval is not one).')),
                ('requests', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'month'), name='arabase_sanad_usage_month')],
            },
        ),
    ]
