# Generated by Django 5.2.17 on 2026-09-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arabase", "0021_sanad_budget"),
        ("dashboard", "0005_widget_grid_12_appearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        db_default="",
                        default="",
                        help_text="Plain text under the title. Line breaks are kept.",
                        max_length=2000,
                    ),
                ),
                (
                    "text_style",
                    models.CharField(
                        choices=[
                            ("section", "Section heading"),
                            ("note", "Note"),
                            ("callout", "Callout"),
                        ],
                        db_default="note",
                        default="note",
                        help_text="A section heading, a note card or a highlighted callout.",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
        migrations.AlterField(
            model_name="chartwidget",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("bar", "Bar"),
                    ("horizontal_bar", "Horizontal bar"),
                    ("line", "Line"),
                    ("area", "Area"),
                    ("pie", "Pie"),
                    ("doughnut", "Doughnut"),
                ],
                db_default="bar",
                default="bar",
                help_text="How the aggregation is drawn.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="progresswidget",
            name="display_style",
            field=models.CharField(
                choices=[("bar", "Bar"), ("ring", "Ring"), ("gauge", "Gauge")],
                db_default="bar",
                default="bar",
                help_text="Whether progress is drawn as a bar, a ring or a gauge.",
                max_length=8,
            ),
        ),
    ]
