# Generated by Django 5.2.17 on 2026-09-29 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import jadawel.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("arabase", "0022_dashboard_text_widget_and_styles"),
        ("dashboard", "0005_widget_grid_12_appearance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedDashboard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("link", "Link"),
                            ("remote", "Remote"),
                        ],
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="`remote` only: the other server, as `https://host[:port]`.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="`link` and `remote`: the slug of the public link.",
                        max_length=128,
                    ),
                ),
                (
                    "granted_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="`link` only: the link's password hash when the user was let in. Access lasts while it still matches, so changing the password or adding one asks the user again. Never the password itself.",
                        max_length=128,
                    ),
                ),
                (
                    "password_sealed",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="`remote` only: the password, sealed (`arabase.sealing`), to get a new token when the other server's expires.",
                    ),
                ),
                (
                    "remote_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="`remote` only: the other server's current access token.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The last known name.",
                        max_length=255,
                    ),
                ),
                (
                    "preview",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The last known layout: `[{type, width, height}]` per widget.",
                    ),
                ),
                (
                    "problem",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="`remote` only: why the last request failed (`password`, `unavailable`, `unreachable`); empty once it works.",
                        max_length=32,
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        help_text="`workspace` only.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dashboard.dashboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source", "workspace")),
                        fields=("user", "dashboard"),
                        name="arabase_saved_dashboard_workspace_once",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("source__in", ["link", "remote"])),
                        fields=("user", "origin", "slug"),
                        name="arabase_saved_dashboard_link_once",
                    ),
                ],
            },
        ),
    ]
