# Generated by Django 5.2.17 on 2026-10-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arabase", "0023_saved_dashboards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("automation", "Automations"),
                            ("builder", "Applications"),
                            ("sanad", "Sanad"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "everyone",
                    models.BooleanField(
                        default=False, help_text="Every user may use the feature."
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("feature",),
            },
        ),
        migrations.CreateModel(
            name="FeatureAccessGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("automation", "Automations"),
                            ("builder", "Applications"),
                            ("sanad", "Sanad"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Normalized like a user's email: lower case.",
                        max_length=254,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("feature", "email"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature", "email"), name="arabase_feature_grant_unique"
                    )
                ],
            },
        ),
    ]
