# Generated by Django 5.2.13 on 2026-09-08 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jadawel_billing",
            "0011_billingorder_purpose_billingorder_subscription_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrefund",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billingrefund",
            name="last_error",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="billingrefund",
            name="operation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="billingrefund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
