# Generated by Django 5.2.16 on 2026-09-02 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_jadawel_rename_show_help_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLastViewedItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_type", models.CharField(max_length=64)),
                ("item_id", models.PositiveIntegerField()),
                ("last_viewed", models.DateTimeField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_viewed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "application"], name="lastviewed_user_app_idx"
                    ),
                    models.Index(
                        fields=["item_type", "item_id"], name="lastviewed_item_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item_type", "item_id"),
                        name="unique_user_last_viewed_item",
                    )
                ],
            },
        ),
    ]
