# Generated by Django 5.2.16 on 2026-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_userlastvieweditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferences",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text="Values of the registered user preference types, keyed by type. Only explicitly changed preferences are stored here.",
            ),
        ),
    ]
