# Generated by Django 5.2.17 on 2026-10-01 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import jadawel.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_jadawel_rename_show_help_request"),
        ("integrations", "0030_jadawel_rename_local_jadawel_pg_objects"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreResponseService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "status_code",
                    jadawel.core.formula.field.FormulaField(
                        blank=True,
                        default="",
                        help_text="The HTTP status code to return.",
                        null=True,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("json", "JSON"),
                            ("text", "Text"),
                        ],
                        default="empty",
                        help_text="The type of response body to return.",
                        max_length=10,
                    ),
                ),
                (
                    "body",
                    jadawel.core.formula.field.FormulaField(
                        blank=True,
                        default="",
                        help_text="The response body content.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
        migrations.AddField(
            model_name="corehttptriggerservice",
            name="response_timeout_seconds",
            field=models.PositiveSmallIntegerField(
                db_default=10,
                default=10,
                help_text="The maximum time to wait for the workflow response in seconds.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Value cannot be less than 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        20,
                        message="Value exceeds the maximum workflow response timeout.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="corehttptriggerservice",
            name="wait_for_response",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether the caller should wait for the workflow response.",
            ),
        ),
        migrations.CreateModel(
            name="CoreResponseHeader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(help_text="The header key.", max_length=255)),
                (
                    "value",
                    jadawel.core.formula.field.FormulaField(
                        blank=True, default="", help_text="The header value.", null=True
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="integrations.coreresponseservice",
                    ),
                ),
            ],
        ),
    ]
