# Generated by Django 5.2.17 on 2026-10-01 16:49

import django.db.models.deletion
from django.db import migrations, models

import jadawel.contrib.integrations.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_jadawel_rename_show_help_request"),
        ("integrations", "0031_response_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreInboundEmailTriggerService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=jadawel.contrib.integrations.core.models.generate_inbound_email_token,
                        help_text="The localpart of the generated inbound email address.",
                        max_length=32,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Defines whether the service is published or not.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
