# Generated by Django 5.2.13 on 2026-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadawel_billing", "0006_backfill_payment_attempts"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_payment_id__isnull", False)),
                fields=("provider_payment_id",),
                name="billing_unique_provider_payment",
            ),
        ),
    ]
