# Generated by Django 5.2.12 on 2026-03-24 07:45

from django.db import migrations, models

import jadawel.contrib.builder.elements.models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0068_jadawel_rename_local_jadawel_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuelement",
            name="variant",
            field=models.JSONField(
                blank=True,
                db_default={
                    "desktop": "expanded",
                    "smartphone": "compact",
                    "tablet": "compact",
                },
                default=jadawel.contrib.builder.elements.models.get_default_variant,
                help_text=(
                    "The menu variant (expanded or compact) for each device type"
                ),
            ),
        ),
    ]
