# Generated by Django 5.2.14 on 2026-06-16 15:34

from django.db import migrations, models

import jadawel.contrib.builder.elements.models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0069_menuelement_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnelement",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("1:2", "Ratio 1 2"),
                    ("2:1", "Ratio 2 1"),
                    ("1:3", "Ratio 1 3"),
                    ("3:1", "Ratio 3 1"),
                    ("1:1:2", "Ratio 1 1 2"),
                    ("2:1:1", "Ratio 2 1 1"),
                    ("1:2:1", "Ratio 1 2 1"),
                    ("custom", "Custom"),
                ],
                db_default="auto",
                default="auto",
                help_text="The layout type determining column weights.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="columnelement",
            name="column_weights",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text=(
                    "Custom weight configuration for each column. Used when "
                    "layout_type is 'custom'."
                ),
            ),
        ),
        migrations.AddField(
            model_name="columnelement",
            name="column_stacking",
            field=models.JSONField(
                blank=True,
                db_default={
                    "desktop": "horizontal",
                    "smartphone": "stacked",
                    "tablet": "horizontal",
                },
                default=(
                    jadawel.contrib.builder.elements.models.get_default_column_stacking
                ),
                help_text=(
                    "Whether columns are horizontal or stacked for each device type."
                ),
            ),
        ),
    ]
