# Generated by Django 5.2.13 on 2026-09-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadawel_billing", "0003_billingorder_subscription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100)),
                ("mode", models.CharField(max_length=4)),
                ("payment_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=60)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "mode"),
                        name="billing_unique_provider_event",
                    )
                ],
            },
        ),
    ]
